# This workflow retrieves the latest version of a Docker image from Docker Hub
name: get-latest-version-docker-image

on:
 workflow_call:
  inputs:
    repository_name:
      required: true
      description: 'Name of the repository where the image will be pushed'
      type: string
    namespace:
      required: true
      description: 'Namespace from Docker Hub where the image will be pushed'
      type: string
  
  secrets:
    username:
      required: true
      description: 'Docker Hub username'
    password:
      required: true
      description: 'Docker Hub password'

jobs:
  get-latest-version:
    runs-on: ubuntu-latest

    outputs:
      latest_version: ${{ steps.get-latest-version.outputs.latest_version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        
    - name: Get latest version from Docker Hub
      id: get-latest-version
      run: |
        LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/namespaces/${{inputs.namespace}}/repositories/${{inputs.repository_name}}/tags" | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        echo "Latest version: $LATEST_VERSION"
        echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
  